### ISSUE TITLE
Any way to present a data.frame to choose a row from?

### ISSUE THREAD

**Issue by sckott** [gaborcsardi/ask#11]
I'm looking for a solution for a problem in a package I have where a function loops over a vector of inputs, some of the elements of which will require a user to give feedback in a prompt, but after they've picked a choice from the prompt, I'd like the prompt and associated info to disappear. 

Seems like you have this solution in this pkg with e.g. this

```r
ask(
  size = choose("What size do you need?", c("Large", "Medium", "Small"))
)
```

But is it possible to present a data.frame in the eg above, and the user picks a row? And after picking the data.frame disappears.  

If not, I'm thinking of a way to compactly present just the most important information in a string that can fit in the format above

**Comment by gaborcsardi** [comment]
I guess you can turn each data frame row into a string, but after the choices are  cleared, the output is not really nice:
```r
txt <- capture.output(iris[1:10,])[-1]
names(txt)  <- 1:10
sel  <- ask::ask(row = choose("Which one do you want?", txt))
```

```
❯ Which one do you want? 7           4.6         3.4          1.4         0.3  setosa
```

**Comment by sckott** [comment]
Right, good idea. Sounds like best approach will be to see if my use case can fit into strings being passed to `choose()` , i'll try that
